"""Retrieval over mission knowledge: metadata filter, then lexical score,
then a bounded budget. No embeddings, and the reason is not squeamishness.

WHY NOT A VECTOR STORE, ARGUED RATHER THAN ASSERTED
------------------------------------------------------
`tower/memory.py` already states this repository's position for the causal
chain: similarity is not causation. This module retrieves over a different
corpus and reaches the same conclusion for a different reason, so the
argument is made again from scratch rather than inherited.

The corpus here is machine-written. Every `statement` in it is generated by
`recall/distill.py` from typed fields, using a fixed sentence template per
`RecordKind`. It therefore has a vocabulary of a few hundred terms, no
synonymy that was not put there deliberately, and no paraphrase at all.
Embeddings buy exactly one thing over term matching -- recall across
different wordings of the same idea -- and there are no different wordings
here to recover. What an embedding would ADD is a model call in the
retrieval path (so retrieval stops working when Vertex is down, which the
whole T0/T1 architecture exists to prevent), a floating-point index to keep
consistent with Firestore, and a scoring function no judge can check by
reading it.

What retrieval here actually has to be good at is the thing embeddings are
weakest at: EXACT SUBJECT MATCH WITH METADATA FILTERS. "Everything ever
recorded about `fleet_recon`, cautions only, most recent first" is a filter
and a term match. A nearest-neighbour search answers it with `fleet_risk`'s
records ranked plausibly high.

If the corpus ever carries human free text -- an operator's note, a
counterparty email -- that argument stops holding and this module should
gain an embedding path. `docs/architecture.md` records that condition
explicitly so the decision is revisited on a trigger rather than on taste.

THE SCORING FUNCTION, IN FULL
--------------------------------
A BM25-shaped lexical score, small enough to read:

    score(record) = SUM over query terms of
        idf(term) * (tf * (k1 + 1)) / (tf + k1 * (1 - b + b * len/avglen))

plus two explicit, named boosts that are NOT part of BM25 and are stated
rather than folded into the weights:

    SUBJECT BOOST   -- a term matching the record's `subject` exactly is
                       worth more than the same term in prose, because the
                       subject is an identifier and prose is description.
    RECENCY TIEBREAK -- ordering only, never magnitude. Two records with
                       equal score sort newest-first. Recency does not
                       promote a worse match above a better one, which is
                       the failure mode of folding time into the score.

THE BUDGET IS THE POINT
--------------------------
`search` takes `k` AND `char_budget`, and returns how many records it
dropped for each. A caller that asks for the top 5 of 500 records gets 5,
and `RetrievalResult.considered` says 500, so "this does not put the whole
corpus in a prompt" is a number in the response rather than a claim in a
README. `tests/test_recall_index.py::test_retrieval_selects_rather_than_loading`
asserts it against a 500-record corpus.

Pure functions. No clock (callers pass `now`), no network, no model.
"""

from __future__ import annotations

import math
import re
from datetime import UTC, datetime
from typing import Any

from recall.schema import (
    KnowledgeRecord,
    RecordKind,
    RetrievalResult,
    RetrievedRecord,
    Standing,
)

#: [ASSUMPTION] BM25 constants. The literature's usual defaults; stated as
#: chosen rather than tuned, because tuning them against this corpus would be
#: fitting a ranking function to the four scenarios it is demonstrated on.
_K1 = 1.5
_B = 0.75

#: [ASSUMPTION] A term that matches the record's `subject` exactly counts
#: this many times over in the term frequency. Chosen legibly: an identifier
#: match is worth roughly three prose mentions.
_SUBJECT_BOOST = 3.0

#: Tokens carrying no discriminating power in a corpus this narrow. Kept
#: deliberately short -- an aggressive stop list is a silent recall cut.
_STOPWORDS = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "by",
        "for",
        "from",
        "in",
        "is",
        "it",
        "of",
        "on",
        "or",
        "that",
        "the",
        "to",
        "was",
        "were",
        "what",
        "which",
        "with",
    }
)

_TOKEN = re.compile(r"[a-z0-9_.]+")


def tokenize(text: str) -> list[str]:
    """Lowercase, split on non-identifier characters, drop stopwords.

    `.` and `_` are kept INSIDE tokens on purpose: `fleet_recon`,
    `finance.secret_read` and `clm_tariff_rate_K` are single identifiers and
    splitting them would turn a precise subject match into three vague ones.
    """
    return [t for t in _TOKEN.findall(text.lower()) if t and t not in _STOPWORDS]


def _record_terms(record: KnowledgeRecord) -> list[str]:
    """The searchable text of one record: its statement plus its identifiers.

    Identifiers are appended rather than relied on inside the statement,
    because a statement is prose and a filter needs the identifier present
    whether or not the sentence happens to mention it.
    """
    return tokenize(
        " ".join(
            [
                record.statement,
                record.subject,
                record.kind.value,
                record.agent_id,
                record.tool,
                record.source,
            ]
        )
    )


def _passes_filters(
    record: KnowledgeRecord,
    *,
    kinds: set[RecordKind] | None,
    standings: set[Standing] | None,
    subjects: set[str] | None,
    objective_class: str | None,
    max_age_seconds: float | None,
    now: datetime,
) -> bool:
    if kinds is not None and record.kind not in kinds:
        return False
    if standings is not None and record.standing not in standings:
        return False
    if subjects is not None and record.subject not in subjects:
        return False
    if objective_class is not None and record.objective_class != objective_class:
        return False
    if max_age_seconds is not None:
        observed = record.observed_at
        if observed.tzinfo is None:
            observed = observed.replace(tzinfo=UTC)
        if (now - observed).total_seconds() > max_age_seconds:
            return False
    return True


def search(
    query: str,
    records: list[KnowledgeRecord],
    *,
    k: int = 5,
    char_budget: int = 2000,
    kinds: set[RecordKind] | None = None,
    standings: set[Standing] | None = None,
    subjects: set[str] | None = None,
    objective_class: str | None = None,
    max_age_seconds: float | None = None,
    now: datetime | None = None,
) -> RetrievalResult:
    """Filter, score, bound. Returns what was selected and what was not.

    `standings` defaults to everything EXCEPT `UNTRUSTED`. A caller wanting
    untrusted records must ask for them by name, so no accidental path
    exists by which a record marked untrusted reaches a planner.
    """
    now = now or datetime.now(UTC)
    if standings is None:
        standings = {Standing.OBSERVED, Standing.CAUTION}

    considered = len(records)
    candidates = [
        r
        for r in records
        if _passes_filters(
            r,
            kinds=kinds,
            standings=standings,
            subjects=subjects,
            objective_class=objective_class,
            max_age_seconds=max_age_seconds,
            now=now,
        )
    ]
    filtered_out = considered - len(candidates)

    query_terms = tokenize(query)
    if not candidates or not query_terms:
        return RetrievalResult(
            query=query,
            selected=[],
            considered=considered,
            filtered_out=filtered_out,
            dropped_for_budget=0,
            zero_scored=len(candidates),
            chars_returned=0,
            char_budget=char_budget,
            filters=_filter_record(kinds, standings, subjects, objective_class, max_age_seconds, k),
        )

    docs = [_record_terms(r) for r in candidates]
    lengths = [len(d) for d in docs]
    avg_len = (sum(lengths) / len(lengths)) or 1.0
    n_docs = len(docs)

    # Document frequency per query term, computed over the FILTERED corpus:
    # idf must describe the population actually being ranked, not the whole
    # store, or a term common in the store and rare among the candidates
    # gets scored as though it were uninformative.
    doc_freq: dict[str, int] = {}
    doc_sets = [set(d) for d in docs]
    for term in set(query_terms):
        doc_freq[term] = sum(1 for s in doc_sets if term in s)

    scored: list[tuple[float, list[str], KnowledgeRecord]] = []
    for record, doc, length in zip(candidates, docs, lengths, strict=True):
        score = 0.0
        matched: list[str] = []
        subject_tokens = set(tokenize(record.subject))
        for term in query_terms:
            tf = float(doc.count(term))
            if term in subject_tokens:
                tf += _SUBJECT_BOOST
            if tf <= 0:
                continue
            df = doc_freq.get(term, 0)
            # BM25's idf, with the +1 that keeps it non-negative for a term
            # present in every document.
            idf = math.log(1.0 + (n_docs - df + 0.5) / (df + 0.5))
            denom = tf + _K1 * (1.0 - _B + _B * (length / avg_len))
            score += idf * (tf * (_K1 + 1.0)) / denom
            matched.append(term)
        if score > 0:
            scored.append((score, sorted(set(matched)), record))

    zero_scored = len(candidates) - len(scored)

    # Sort by score, then newest-first as a pure tiebreak, then by record_id
    # so the order is total and therefore reproducible.
    def _sort_key(item: tuple[float, list[str], KnowledgeRecord]):
        score, _, record = item
        observed = record.observed_at
        if observed.tzinfo is None:
            observed = observed.replace(tzinfo=UTC)
        return (-round(score, 9), -observed.timestamp(), record.record_id)

    scored.sort(key=_sort_key)

    selected: list[RetrievedRecord] = []
    chars = 0
    dropped = 0
    for score, matched, record in scored:
        cost = len(record.statement)
        if len(selected) >= k or chars + cost > char_budget:
            dropped += 1
            continue
        selected.append(
            RetrievedRecord(record=record, score=round(score, 6), matched_terms=matched)
        )
        chars += cost

    return RetrievalResult(
        query=query,
        selected=selected,
        considered=considered,
        filtered_out=filtered_out,
        dropped_for_budget=dropped,
        zero_scored=zero_scored,
        chars_returned=chars,
        char_budget=char_budget,
        filters=_filter_record(kinds, standings, subjects, objective_class, max_age_seconds, k),
    )


def _filter_record(
    kinds: set[RecordKind] | None,
    standings: set[Standing] | None,
    subjects: set[str] | None,
    objective_class: str | None,
    max_age_seconds: float | None,
    k: int,
) -> dict[str, Any]:
    """Exactly what was asked for, echoed back. A retrieval whose filters are
    not in its own result cannot be audited after the fact."""
    return {
        "kinds": sorted(x.value for x in kinds) if kinds else None,
        "standings": sorted(x.value for x in standings) if standings else None,
        "subjects": sorted(subjects) if subjects else None,
        "objective_class": objective_class,
        "max_age_seconds": max_age_seconds,
        "k": k,
    }


__all__ = ["search", "tokenize"]
